### ISSUE TITLE
pasting number doesn't select correct country

### ISSUE THREAD

**Issue by samthomson** [mukeshsoni/react-telephone-input#320]
1. click in to input
2. press ctrl + A
3. paste in from clipboard '4522594586'

Expectation: Danish flag is selected, with the number component 22594586
Reality: US flag is shown, and number 122594586

Note: This only happens the first time, second time round it works as expected. Reloading the page brings it back to the initial problematic state.

Seems related to but different from this issue as https://github.com/mukeshsoni/react-telephone-input/issues/201 (not just Danish numbers though, I can reproduce on all numbers). 

If this can't be fixed, perhaps a prop to disable autoparsing of country code would help.

Thanks.

**Comment by mukeshsoni** [comment]
@samthomson Can you open a PR for adding a prop for disabling auto parsing of country code?

**Comment by samthomson** [comment]
Sure, but in that case I'll look to fix handling the initial pasted value (unless you know that to be a dead end) since that where the bug is.
I just pulled down the project and ran as per instructions at base of read me and got an error:

![image](https://user-images.githubusercontent.com/6588340/80618128-74c09f00-8a32-11ea-8b24-5cf536b64694.png)

Can you confirm following those instructions work for you (ie clone in to new directory, then `npm i && npm run start`) or advise on local development?

Thanks.

**Comment by mukeshsoni** [comment]
Have pushed a fix for the build. You can pull the latest master.

**Comment by mukeshsoni** [comment]
@samthomson I am changing the testing library as well as fixing a number of other bugs. 

You can checkout the PR here - https://github.com/mukeshsoni/react-telephone-input/pulls

You can use the `bugfixes` branch which is now stable. It will build properly as well as all the tests pass. I will merge to master soon.

**Comment by mukeshsoni** [comment]
@samthomson I could not reproduce it in 4.75.5. Might have been fixed with other bug fixes i made.

**Comment by samthomson** [comment]
Hey, getting to this now,
Just updated to v 5, still an issue sadly. Please re-open the issue and I'll start on a PR.

Unfortunately the local demo/test page doesn't seem to work (no build errors this time, just blank screen rendered):
![image](https://user-images.githubusercontent.com/6588340/80983328-f8f09900-8e1b-11ea-91de-ebd1955dfa01.png)
Any ideas?

**Comment by samthomson** [comment]
(it does appear the app has built successfully)
![image](https://user-images.githubusercontent.com/6588340/80983582-3a814400-8e1c-11ea-92b4-0e3a93fabbe6.png)

**Comment by mukeshsoni** [comment]
Oh. Didn't know the demo was broken. Let me take a look.

**Comment by mukeshsoni** [comment]
@samthomson Have fixed the demo server thing. You should see the demos now.

**Comment by samthomson** [comment]
Can confirm the issue was in my code base. Sorry for wasting your time. A related component was changing the state of your phone input :sweat: 
Thanks for helping, and good to know you're open to PRs for the future :+1:

**Comment by mukeshsoni** [comment]
No problem. Glad you found the issue.
